# This is a basic workflow to help you get started with Actions

name: invoke

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
          release:
              description: 'github link to raw manifest (ex internal-dev, internal-test, release)'
              required: true

env:
    RELEASE: ${{ github.event.inputs.release || github.event.client_payload.release  }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    invokerelease:
      runs-on: ubuntu-latest
      steps:
        - name: Run release train against internal test
          uses: peter-evans/repository-dispatch@v1
          with:
              token: ${{ secrets.NATE_GITHUB_BOT_TOKEN }}
              repository: nathanjulsrud/testactions
              event-type: nate-event
              client-payload: '{"release": "${{ env.RELEASE }}"}'
